name: Deploy web to S3
on: workflow_dispatch
jobs: 
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Deploy
        uses: reggionick/s3-deploy@v4
        with:
          folder: mamd-web
          bucket: ${{ secrets.PRODUCTION_S3_BUCKET }}
          bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
          dist-id: ${{ secrets.PRODUCTION_CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /*
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: '{.*/**,**}'